url: http://getakka.net
title: Akka.NET
author: Akka.NET
email: hi@getakka.net
github_url: https://github.com/akkadotnet/akka.net/
issues_url: https://github.com/akkadotnet/akka.net/issues
twitter_handle: AkkaDotNET
twitter_url: https://twitter.com/AkkaDotNET
stack_overflow_url: http://stackoverflow.com/questions/tagged/akka.net
facebook_url: https://www.facebook.com/akkadotnet
google_group_url: https://groups.google.com/forum/#!forum/akkadotnet-user-list
logo_path: /images/akkalogo.png
bootcamp_url: http://learnakka.net